### ISSUE TITLE
Errors with Docker build

### ISSUE THREAD

**Issue by steven-guan** [global-121/121-platform#1668]
Steps before 14 are working. Following are the error logs.

Step 14/22 : RUN apt-get update -y && apt-get install -y         python3-pyzmq=${python3_pyzmq_ver}         indy-plenum=${indy_plenum_ver}         indy-node=${indy_node_ver}         python3-indy-crypto=${python3_indy_crypto_ver}         libindy-crypto=${indy_crypto_ver}         vim

 ---> Running in 0a87651b9f9f
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:5 https://repo.sovrin.org/deb xenial InRelease [28.4 kB]
Get:6 https://repo.sovrin.org/deb xenial/master amd64 Packages [345 kB]
Fetched 373 kB in 4s (80.2 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indy-plenum : Depends: python3-orderedset (= 2.0) but 2.0.3 is to be installed
               Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
               Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
               Depends: python3-pympler (= 0.5) but 0.8 is to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'indypool' failed to build: The command '/bin/sh -c apt-get update -y && apt-get install -y         python3-pyzmq=${python3_pyzmq_ver}         indy-plenum=${indy_plenum_ver}         indy-node=${indy_node_ver}         python3-indy-crypto=${python3_indy_crypto_ver}         libindy-crypto=${indy_crypto_ver}         vim' returned a non-zero code: 100
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 121-platform@ start:services: `cd services/ && docker-compose -f docker-compose.yml -f docker-compose.development.yml up -d --build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 121-platform@ start:services script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2020-12-17T15_27_01_774Z-debug.log

**Comment by elwinschmitz** [comment]
There is currently an issue with one of our 'back-back-end'-services, the `indypool`-component.
Due to some issue with a dependency of a dependency it isn't able to build the Docker-image properly.

We (i.e. @jannisvisser ) have found a workaround to continue working with an existing version of the `indypool`-component; but I'm not sure if that is usable by you when you set up a new 'clean' environment.

It should be possible to work with the system(121-service + HO-Portal) without the `tykn-ssi-services`, I think. You could try to remove/comment-out the section from the `docker-compose`-file: https://github.com/global-121/121-platform/blob/master/services/docker-compose.yml#L4-L26
Or also remove/comment-out the `tyknims`, `orgims`, `userims`-components in that file.

I haven't tried it like that locally myself, but maybe it'll get you past the initial set-up hurdles...

**Comment by steven-guan** [comment]
great, after comment-out the tyknims, orgims, userims, finally it passed.

**Comment by RubenGeo** [comment]
This issue is temporarly fixed by this [PR](https://github.com/global-121/121-platform/pull/1713). We are hosing an older version of a docker image of this on our docker hub which is now used in the docker-compose.

**Comment by diderikvw** [comment]
Closing this issue as we have a workaround. Permanent solution: remove Sovrin from the 121 platform.
